version: '3'
services:
  http_server:
    networks:
      - web
    build: .
    image: website
    restart: unless-stopped
    labels:
      - "traefik.http.routers.http-server-website.rule=Host(`website.localhost`)"
    volumes:
      - "${PWD}/server/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/server/logs/:/usr/share/nginx/logs/"
networks:
  web:
    external: true
